apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/k3s/helm-releases
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: strimzi
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: strimzi
      namespace: flux-system
