apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: extra-kustomizations
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/k3s/kustomizations
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system