apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: lsst-drp-kafka
  chart:
    spec:
      chart: prometheus
      version: "27.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-source
        namespace: flux-system